### ISSUE TITLE
Pablo enviar caminho dos dados da rodada FV3 para Bárbara

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#17]

**Comment by afrassoni** [comment]
Caminho dos dados:
/mnt/beegfs/julio.fernandez/FV3/bench (18Gb)

**Comment by afrassoni** [comment]
@barbarayamada esta tarefa já foi concluída?

**Comment by CGCT-CPTEC-DIMNT** [comment]
Oi Ariane. É para copiar os dados que estão nesse diretório que você passou, para a área DMDDADOS? Caso afirmativo, preciso acessar a área para verificar, e por enquanto estou sem acesso devido ao problema com o notebook de trabalho.

**Comment by afrassoni** [comment]
@barbarayamada esta tarefa já foi concluída?

**Comment by barbarayamada** [comment]
Oi Ariane!

O Pablo enviou este caminho  /share/wrf/dist/ERA5.

**Comment by barbarayamada** [comment]
/mnt/beegfs/julio.fernandez/FV3/bench/ASSESSMENT

Os dados do MPAS estão a cada 10 dias, mas os dados do FV3 estão a cada 5 dias.
Para compatibilizar, usaremos os casos a cada 10 dias. Se tiver tempo hábil, o Pablo completará as rodadas do MPAS e fará a cada 5 dias. 

Avisaremos ao Rozante, sobre essa ampliação do número de casos de rodadas.

**Comment by barbarayamada** [comment]
Pessoal, 

Todas as previsões pós-processadas do modelo SHiELD 13 km estão disponíveis em:

 /mnt/beegfs/julio.fernandez/FV3/bench/ASSESSMENT

Os dados estão interpolados para 0.25x0.25 como os dados do ERA5. Tem um README.1st para alguns detalhes. Tem 74 previsões para cada modelo forcado com dados do ERA5, iniciadas o 00Z01JUN2021 até 00Z01JUN2022, previsões a cada 5 dias. 

Também, foram incluídos os ctl para os dados grib do ERA5

/mnt/beegfs/julio.fernandez/ERA5/pressure

Abraço,

Pablo

**Comment by marcelobarbio** [comment]
As rodadas acima já foram apresentadas no último workshop.

**Comment by CGCT-CPTEC-DIMNT** [comment]
Os dados do diretório:
/mnt/beegfs/julio.fernandez/FV3/bench/ASSESSMENT
foram copiados para o diretório:
pesq/dados/dmddados/gam/modelos/fv3/ASSESSMENT

Os dados do diretório:
/mnt/beegfs/julio.fernandez/FV3/bench/CASES
foram copiados para o diretório:
pesq/dados/dmddados/gam/modelos/fv3/CASES

**Comment by afrassoni** [comment]
@barbarayamada podemos fechar essa tarefa? Se sim, precisa atualizar a wiki do repo MONAN

**Comment by barbarayamada** [comment]
@afrassoni podemos sim. Wiki do repositório MONAN atualizada

https://github.com/GAM-DIMNT-CPTEC/MONAN/wiki/MONAN
