### ISSUE TITLE
Elaboração do relatório MONAN

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#24]
Relatório sobre os resultados da avaliação dos modelos globais para o projeto MONAN

**Comment by afrassoni** [comment]
Assuntos a serem adicionados no relatório:

- Deficiência do pós-processamento do MPAS
- SHiELD tem pós-processamento disponível e de fácil utilização

**Comment by afrassoni** [comment]
Pessoal, boa tarde.
Acabei de conversar com o Saulo sobre a entrega do relatório.
Ele vai tirar férias entre 01 a 10/07, e por isso quer que adiantemos o relatório.
Vamos entregar o que temos até agora, com as análises das avaliações objetivas da precipitação, do geopotencial produzido pelo Pablo e a análise do Mahalanobis. As demais análises serão realizadas posteriormente, em um segundo relatório. Assim teremos mais tempo para produzir o restante do material.

O prazo solicitado pelo Saulo é **dia 26/06**, próxima **segunda-feira**. 

Proponho que incluamos os tópicos discutidos na nossa reunião de terça-feira. Cada um fazendo sua contribuição até sexta-feira, 23/06, dá tempo para eu revisar e fazer ajustes necessários. 

As figuras solicitadas para a Bárbara poderão ser feitas com calma, sem necessidade de entregar este material neste momento.

Qualquer dúvida, comentem abaixo.

Abraços

**Comment by afrassoni** [comment]
Adicionando o arquivo provido pelo Marcelo referente à discussão dos resultados do Mahalanobis. 



[202306-mahalanobis.pdf](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/11840601/202306-mahalanobis.pdf)

**Comment by afrassoni** [comment]
Email enviado ao Saulo

Boa noite Saulo,

Segue em anexo o relatório do GAM. 
Também envio a análise realizada pelo Pablo para as avaliações de altura geopotencial. 
Este último documento será incorporado ao relatório, pois é preciso transferi-lo para o formato LaTeX.

Abs,
Ariane

[Analise_Z500hPa_MPAS_vs_SHiELD_2021-2022_26Jun23.pdf](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/11875365/Analise_Z500hPa_MPAS_vs_SHiELD_2021-2022_26Jun23.pdf)



[MPAS_FV3_relatorio.pdf](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/11875369/MPAS_FV3_relatorio.pdf)

**Comment by barbarayamada** [comment]
O documento AVALIAÇÃO DE MODELOS GLOBAIS PARA O PROJETO MONAN: RESULTADOS PRELIMINARES já está completo ou precisa inserir ainda tudo que falta do arquivo Protocolo_MONAN_GAM_v1.7.docx?
E a Tabela 3: Variáveis contínuas e dicotômicas a serem avaliadas, eu já não havia feito? Estava errada? Onde está o código de criação dessa tabela? Vc guardou em algum lugar? Achei que tivesse visto o código em algum lugar

**Comment by afrassoni** [comment]
Bom dia a todos.
A primeira parte do relatório foi submetida para a biblioteca. O texto ainda pode ser alterado, e por isso, gostaria de pedir que por favor façam uma revisão geral do texto até dia 12 de setembro. 
Obrigada

[MPAS_FV3_relatorio.pdf](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/12499153/MPAS_FV3_relatorio.pdf)

**Comment by barbarayamada** [comment]
Bom dia @afrassoni. 
A Figura 3.5 - Series temporais da ACC do geopotencial a 500 hPa dos modelos MPAS (vermelho) e SHiELD (azul), para o Hemisfério Norte (painel superior), trópicos (médio) e Hemisfério Sul (painel inferior). Previsões de 120 h (5dias) para o período de junho 2021 a maio 2022 (74 casos). . . . . . . . . da página 32 está super ampliada. **RESOLVIDO**

A Tabela 2.1 - Características dos modelos e das integrações numéricas realizadas. wall-clock time significa o tempo de processamento para 24h de previsão. . . . da página 8 está sem borda inferior. **RESOLVIDO**

A Tabela 2.2 - Parametrizações físicas dos modelos SHiELD e MPAS da pág. 9 está na última linha com borda lateral, mas sem demais bordas e tb sem texto. **RESOLVIDO**

A Tabela 3.1 - Pontuações atribuídas às métricas relacionadas a opções de funcionalidades. da pág. 14 está com um título adicional em negrito. Idem para as Tabelas 3.2 e 3.3. **RESOLVIDO**

O tamanho da fonte da Tabela 3.5 da pág. 17 está muito grande. Idem para a Tabela 3.6 da pág. 18. **RESOLVIDO**

A Figura 3.3 da pág. 30 não tem como Fonte: Produção própria? Idem para as Figuras 3.5, 3.6, 3.7 e 3.8. **RESOLVIDO**

**Comment by barbarayamada** [comment]
No SUMÁRIO no item 3.4 Análise Multivariada de MH . . . . . . . . . . . . . . . . . . . . . . . . . 20, seria melhor escrever Análise Multivariada de Mahalanobis, uma vez que a sigla MH para Mahalanobis, só aparece na página 11 do relatório **RESOLVIDO**

**Comment by barbarayamada** [comment]
1 Introdução
O presente documento tem por objetivo apresentar a primeira etapa do processo
de avaliação **da** funcionalidade de software dos modelos numéricos de escala global
visando a escolha da componente atmosférica do Model for Ocean-laNd-Atmosphere
predictioN (MONAN).

Entre os **Atributos de Qualidade**, o Grupo de Avaliação de Modelos da Divisão de Modelagem Numérica do Sistema Terrestre (GAM-DIMNT) está preocupado com **o Aspecto da Funcionalidade e da Usabilidade**. Entende-se por Funcionalidade a capacidade de um software de satisfazer as necessidades de seu usuário, sejam elas declaradas ou implícitas, por meio do provimento de funcionalidades, dentro de um determinado contexto de uso (ISO/IEC 9126, Wikipedia, 2022).

**1.1 Funcionalidade**
O Aspecto **da** Funcionalidade possui as seguintes subcaracterísticas (WIKIPEDIA, 2022):

Dentre as subcaracterísticas listadas **da Funcionalidade**, o GAM-DIMNT se propôs a elaborar e aplicar métricas ou utilizar ferramentas existentes para as três primeiras, a saber: Adequação, Acurácia e Interoperabilidade.  **Do mesmo modo será feito com relação às seguintes subcaracterísticas da Usabilidade: Inteligibilidade, Operacionalidade e Capacidade de Colaboração.** **Esta última subcaracterística não encontrei na respectiva referência**

**1.1.1 Análise da Funcionalidade: subcaracterísticas**

**A subcaracterística Adequação é a capacidade do produto de software de prover um conjunto apropriado de funções para tarefas e objetivos do usuário especificados.** **Esta definição está repetitiva. Já foi definida no início da mesma página, pág. 2**  O MONAN é um modelo comunitário, desenvolvido com apoio de diversas instituições, sob a liderança do **Instituto Nacional de Pesquisas Espaciais (INPE)** . 

Portanto, a subcaracterística Adequação deverá indicar qual núcleo dinâmico tem a capacidade de compor o modelo MONAN, visando cumprir a necessidade de atender às escalas global, regional e futuramente, **à** escala local.  **Creio que este último "a" tem crase**

**A subcaracterística Interoperabilidade indica a capacidade do produto de software de interagir com um ou mais sistemas especificados.** **Já foi definida na página, pág. 2** No caso do MONAN, espera-se que o núcleo dinâmico escolhido esteja preparado para interagir com outras componentes e/ou aplicações do Sistema Terrestre bem como com o sistema de Assimilação de Dados.

**Comment by barbarayamada** [comment]
Na pág. 4   -   Tendo em vista que o Centro de Previsão de Tempo e Estudos Climáticos (CPTEC) do **INPE** é um centro operacional de previsão numérica, a subcaracterística Operacionalidade é fundamental, e indica que o produto de software deve possibilitar ao usuário operá-lo e controlá-lo, mantendo a proteção frente a erros de usuários.

**1.2 Usabilidade**
A Usabilidade é definida como a capacidade do produto de software de ser compreendido, aprendido, operado e atraente ao usuário, quando usado sob condições especificadas. Note que este conceito é bastante abrangente e se aplica mesmo a programas que não possuem uma interface para o usuário final. Por exemplo, um programa batch executado por uma ferramenta de programação de processos também pode ser avaliado quanto a sua usabilidade, no que diz respeito a ser facilmente compreendido, aprendido etc. 

1.2.1 Análise da Usabilidade: subcaracterísticas

Por fim, a subcaracterística **Capacidade de colaboração** é interpretada como a interação e colaboração com os centros desenvolvedores do núcleo dinâmico em análise.  **Onde acho esta subcaracterística nas referências?**

**Comment by afrassoni** [comment]
@barbarayamada posso fechar as tuas contribuições e gerar a nova versão?

**Comment by CGCT-CPTEC-DIMNT** [comment]
@afrassoni   Já conclui minhas contribuições

**Comment by CGCT-CPTEC-DIMNT** [comment]
[

[publicacao.pdf](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/14103943/publicacao.pdf)
