### ISSUE TITLE
Edição da lista de variáveis dos casos MONAN

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#29]
Inseri a lista de variáveis dos casos de estudo na wiki do MONAN. Gostaria de pedir uma colaboração:

@Julio Pablo @Bárbara Yamada quando puderem contribuir para inserir uma breve descrição na lista das variáveis, agradeço

**Comment by barbarayamada** [comment]
Lista de variáveis do MPAS assesment, FV3 assesment e cases concluídas. Somente falta lista de variáveis do MPAS cases e comparação entre as variáveis do MPAS e FV3.

**Comment by barbarayamada** [comment]
Lista de variáveis do MPAS cases Bahia concluída. Falta MPAS Cases Raoni e comparação entre as variáveis do MPAS e FV3.

**Comment by barbarayamada** [comment]
Lista de variáveis do MPAS e FV3 concluídas. Falta realizar a comparação entre as variáveis do MPAS e FV3.

**Comment by barbarayamada** [comment]
Comparação realizada entre as varíáveis disponíveis na área comum de dados, para o FV3 e MPAS, e incluída na wiki do MONAN.

**Comment by barbarayamada** [comment]
@jpablofernandez, criei uma planilha para comparar as variáveis disponíveis, na área comum de dados, para o FV3 com as variáveis para o MPAS. Por favor, você poderia fazer uma revisão dessa tabela? O arquivo compara_variaveis_FV3_MPAS.xlsx está no drive do GAM e pode ser acessado com o link abaixo:

https://docs.google.com/spreadsheets/d/1Jw49Wy0PwICWfnhYmbZdxzB0Pep7j7x6/edit?usp=sharing&ouid=116265476131470823281&rtpof=true&sd=true

**Comment by jpablofernandez** [comment]
@barbarayamada Verifiquei a planilha e esta correta. Aproveito para informar que um novo conjunto de dados foi gerado, especificamente para os casos, foram adicionadas variáveis solicitadas 3D e 2D e também para duas configurações de física (cumulus): new Tiedtke (E5TIED) e Grell-Freitas (E5GF) no diretório: 

/mnt/beegfs/julio.fernandez/MPAS/bench/CASES/NPOST

Os velhos estão no diretório OPOST.

Adicionalmente em anexo as variáveis disponíveis nesses novos dados:

[Cases_MPAS_NEW_DATA.xls](https://github.com/GAM-DIMNT-CPTEC/MONAN/files/12651510/Cases_MPAS_NEW_DATA.xls)

**Comment by afrassoni** [comment]
@barbarayamada @jpablofernandez eu verifiquei superficialmente a tabela compartilhada pela @barbarayamada e encontrei variáveis compatíveis. Os nomes que não são os mesmos, o que é de se esperar.

Será necessário alterar a planilha para compatibilizar, ou seja, indicar quais variáveis são equivamentes/iguais. Minha sugestão é colocar em uma coluna o MPAS e na outra a variável equivalente do SHiELD.
