### ISSUE TITLE
Rodada do MPAS-GF Casos

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#32]
Tarefa referente à execução do MPAS-A utilizando a parametrização convectiva GF para os casos Raoni e Ubá

Solicitação da Chefia:

1) Parameterização de convecção Grell-Freitas: parameterização que será usada no MONAN
2) Alterção da resolução espacial de 15 km para 24 km: devido a recursos computacionais limitados e ATM vai trabalhar nesta resolução horizontal
3) Versão do MPAS: 8.0.1

**Comment by afrassoni** [comment]
Informação do @jpablofernandez enviada por email em 13/09:

"Na minha área os dados dessas simulações foram estruturado em dois diretórios (OPOST, NPOST), no primeiro como originalmente disponibilizado frequência 6 hr e no segundo com as variáveis adicionais e inicialmente com 27 níveis verticais nas 3D e frequência 3h."

@jpablofernandez favor confirmar se as simulações com GF foram realizadas para 15km e com saídas a cada 3h.

**Comment by afrassoni** [comment]
@jpablofernandez favor confirmar o que afirmou no email de 20/09:

"são disponíveis os dois casos (Raoni e Bahia) com duas físicas cumulus (base: suite mesoescale): NewTiedtke e Grell-Freitas com previsões a cada 3 horas por 10 dias e com 27 níveis verticais (/mnt/beegfs/julio.fernandez/MPAS/bench/CASES) com ~2Tb de dados. "

As rodadas para as duas convecções, MPAS-A v6.3, 15km, estão disponíveis, é isso?

**Comment by jpablofernandez** [comment]
@afrassoni sim, as rodadas estão disponíveis para as duas convecções. No diretório (novo pos) frequencia 3h.  /mnt/beegfs/julio.fernandez/MPAS/bench/CASES/NPOST

**Comment by afrassoni** [comment]
@jpablofernandez para confirmar, os dados da rodada mais longa utilizando o GF estão em /mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5GF24km, correto?
os dados em /mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5 são referentes à rodada com o Tiedtke?
