### ISSUE TITLE
Rodada MPAS-GF anual

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#33]
Tarefa referente à execução do MPAS-A utilizando a parametrização convectiva GF para o período de 05/2021 - 05/2022

Solicitação da Chefia:

1) Parameterização de convecção Grell-Freitas: parameterização que será usada no MONAN
2) Alterção da resolução espacial de 15 km para 24 km: devido a recursos computacionais limitados e ATM vai trabalhar nesta resolução horizontal
3) Versão do MPAS: 8.0.1

**Comment by afrassoni** [comment]
Tempo estimado para realizar essa tarefa, segundo o @jpablofernandez, é meados de outubro de 2023, segundo email enviado em 20/09.

**Comment by afrassoni** [comment]
Entrega prevista para o fechamento da tarefa: 16/10/2023

**Comment by afrassoni** [comment]
@jpablofernandez para confirmar, os dados da rodada mais longa utilizando o GF estão em /mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5GF24km, correto?
os dados em /mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5 são referentes à rodada com o Tiedtke?

**Comment by jpablofernandez** [comment]
Diretorios das rodadas:
a) MPAS-15km cumulus: Tiedtke em:
/mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5
b) MPAS-24km cumulus: Grell-Freitas em:
/mnt/beegfs/julio.fernandez/MPAS/bench/ASSESSMENT/ERA5GF24km
