### ISSUE TITLE
Definição da lista de variáveis - MPAS-GF

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#34]
Antes de dar início às novas simulações com o MPAS-A utilizando a parametrização convectiva GF, precisamos analisar a lista de variáveis e verificar se atende os grupos GAM e avaliação da DIPTC

**Comment by afrassoni** [comment]
@jpablofernandez favor enviar aqui a lista de variáveis planejadas para serem pró-processadas nas novas rodadas indicadas nas Tarefas #32 e #33

**Comment by jpablofernandez** [comment]
@afrassoni inicialmente seriam as variáveis disponibilizadas nos estudos de caso. Vide README.cases em:
 
/mnt/beegfs/julio.fernandez/MPAS/bench/CASES

A lista completa de variáveis disponíveis no MPAS-A estão descritas no Apêndice D do "MPAS-Atmosphere Model User's Guide".

**Comment by afrassoni** [comment]
@barbarayamada finalizar a compatibilização das variáveis do SHiELD e MPAS para que possamos escolher as variáveis a serem geradas nas novas rodadas. 

Acrescentar a lista original de variáveis do manual do MPAS no documento (pode usar um software de recorte de pdf ou gerar manualmente)

**Comment by afrassoni** [comment]
A lista de variáveis utilizada pelo GAM será base para a rodada operacional do MPAS na DIMNT.
A lista com as sugestões de variáveis está em https://docs.google.com/document/d/1cEo6c8gDUdWnIAFImAZMLLvfwj_5Na2krhrMmWoW-S8/edit

**Comment by jpablofernandez** [comment]
Níveis disponíveis para variáveis 3D diagnosticas (U, V,  T, Td, Z, RH, W) por default: 925, 850, 700, 500, 250, 200, 100 e 50 hPa. Para outros níveis e variáveis pode ser necessário modificar o código fonte do MPAS ou usar as saídas brutas em coordenadas Z hibrida e converter usando NCL, python ou outros.
