### ISSUE TITLE
Copiar mascara IPCC para area do GAM

### ISSUE THREAD

**Issue by afrassoni** [GAM-DIMNT-CPTEC/MONAN#36]
Jose Roberto disponibilizou a mascada do IPCC no endereco abaixo.
/dados/dmdpesq/roberto.garcia/CommonData/IPCCv4_RegionMasks

Copiar para uma area visivel pelo GAM (poderia ser na area DADOS?).

Colocar descricao da mascara na wiki do repo MONAN.

**Comment by barbarayamada** [comment]
Oi @afrassoni estou sem permissão de acesso ao diretório dmdpesq 
![WhatsApp Image 2024-03-06 at 4 13 32 PM](https://github.com/GAM-DIMNT-CPTEC/MONAN/assets/105692652/63db05f9-0c1c-46ff-bd6d-f8304e88113c)
